// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ASPNETCoreWork.UpdateModels
{
    public partial class DepartmentUpdate
    {

        public string Name { get; set; }
        public decimal Budget { get; set; }
        public DateTime StartDate { get; set; }
        public int? InstructorId { get; set; }
        public DateTime? DateModified { get; set; }
        public bool? IsDeleted { get; set; }

    }
}